# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective ERICK CLEWIS AKA ERICCA CLEWIS THIS PERSON IS TRANSGENDER
ko_fi: # Replace with a single Ko-fi N/A
tidelift: # Replace with a single Tidelift platform-WINDOWS 11/package-BLAME e.g., OPEN MEDIA/TALKING POINT
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay ERICK CLEWIS
issuehunt: # Replace with a single IssueHunt ERICK CLEWIS
otechie: # Replace with a single Otechie username
custom: # Replace with a single custom sponsorship URL
